//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;

    public partial class Order : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            //this.OrderDetailsLists = new HashSet<OrderDetailsList>();
        }

        private int id;
        public int Id { get { return id; } set { id = value; OnPropertyChanged("Id"); } }
        private Nullable<int> customerId;
        public Nullable<int> CustomerId { get { return customerId; } set { customerId = value; OnPropertyChanged("CustomerId"); } }
        private Nullable<System.DateTime> orderCreate;
        public Nullable<System.DateTime> OrderCreate { get { return orderCreate; } set { orderCreate = value; OnPropertyChanged("OrderCreate"); } }
        private Nullable<System.DateTime> dispatchDate;
        public Nullable<System.DateTime> DispatchDate { get { return dispatchDate; } set { dispatchDate = value; OnPropertyChanged("DispatchDate"); } }
        private Customer customer;
        public Customer Customer { get { return customer; } set { customer = value; OnPropertyChanged("Customer"); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ObservableCollection<OrderDetailsList> orderDetailsLists;
        public ObservableCollection<OrderDetailsList> OrderDetailsLists { get { return orderDetailsLists; } set { orderDetailsLists = value; OnPropertyChanged("OrderDetailsLists"); } }

        private Nullable<decimal> totalAmount;
        public Nullable<decimal> TotalAmount { get { return totalAmount; } set { totalAmount = value; OnPropertyChanged("TotalAmount"); } }

        public event PropertyChangedEventHandler PropertyChanged;
        private void OnPropertyChanged(string property)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(property));
            }
        }

    }
}