//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class OrderDetailsList: INotifyPropertyChanged
    {
        private int id;
        public int Id { get { return id; } set { id = value;OnPropertyChanged("Id");}}
        private Nullable<int> productId;
        public Nullable<int> ProductId { get; set; }
        private string productName;
        public string ProductName { get; set; }
        private Nullable<int> quantity;
        public Nullable<int> Quantity { get; set; }
        private Nullable<decimal> price;
        public Nullable<decimal> Price { get { return price; } set { price = value;OnPropertyChanged("Price"); } }
        private Nullable<decimal> value;
        public Nullable<decimal> Value { get { return value; } set { this.value = value;OnPropertyChanged("Value"); }}
        private Nullable<int> orderId;
        public Nullable<int> OrderId { get { return orderId; } set { orderId = value;OnPropertyChanged("OrderId"); } }
        private Order order;
        public Order Order { get { return order; } set { order = value;OnPropertyChanged("Order"); } }

        public event PropertyChangedEventHandler PropertyChanged;
        private void OnPropertyChanged(string property)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(property));
            }
        }
    }
}
