//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Supplier : INotifyPropertyChanged
    {
        private int id;
        public int Id { get { return id; } set { id = value; OnPropertyChanged("Id"); } }
        private string name;
        public string Name { get { return name; } set { name = value; OnPropertyChanged("Name"); } }
        private string street;
        public string Street { get { return street; } set { street = value; OnPropertyChanged("Street"); } }
        private string postcode;
        public string Postcode { get { return postcode; } set { postcode = value; OnPropertyChanged("Postcode"); } }
        private string city;
        public string City { get { return city; } set { city = value; OnPropertyChanged("City"); } }
        private string country;
        public string Country { get { return country; } set { country = value; OnPropertyChanged("Country"); } }
        private string nip;
        public string Nip { get { return nip; } set { nip = value; OnPropertyChanged("Nip"); } }
        private string email;
        public string Email { get { return email; } set { email = value; OnPropertyChanged("Email"); } }
        private string phone;
        public string Phone { get { return phone; } set { phone = value; OnPropertyChanged("Phone"); } }
        private string type;
        public string Type { get { return type; } set { type = value; OnPropertyChanged("Type"); } }
        private decimal turnOver;
        public decimal TurnOver { get { return turnOver; } set { turnOver = value; OnPropertyChanged("TurnOver"); } }

        public event PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyChanged(string property)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(property));
            }
        }

        public override string ToString()
        {
            return $"{Name}";
        }
    }
}
